# Generated by Django 5.1.2 on 2024-11-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_remove_profile_bio_remove_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
